name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run custom build script
        run: |
          chmod +x ./script.sh
          ./script.sh build-cache

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ github.password }}

      - name: Push Docker image
        run: |
          docker tag vexeexpress-server-image:latest ghcr.io/VexeExpress/vexeexpress-server-image:latest
          docker push ghcr.io/VexeExpress/vexeexpress-server:latest
